import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>

                <div className="flex min-h-screen">
                    <aside className="w-64 bg-gray-900 text-gray-200 fixed min-h-screen">
                        <div className="p-4">
                            <h2 className="text-2xl font-semibold text-white">Iconic UI</h2>
                        </div>
                        <nav className="p-4">
                            <ul>
                                <li className="mb-4">
                                    <a href="/" className="block text-gray-400 hover:text-white">Inicio</a>
                                </li>                                
                                <li className="mb-4">
                                    <a href="/docs/button" className="block text-gray-400 hover:text-white">Button</a>
                                </li>
                                <li className="mb-4">
                                    <a href="/docs/datepicker" className="block text-gray-400 hover:text-white">Date Picker</a>
                                </li>
                                <li className="mb-4">
                                    <a href="/docs/input" className="block text-gray-400 hover:text-white">Input</a>
                                </li>
                            </ul>
                        </nav>
                    </aside>

                    <main className="flex-1 p-8 bg-slate-700 ps-72">
                        <div className="rounded-lg shadow">
                            {children}
                        </div>
                    </main>
                </div>

            </body>
        </html>
    )
}
